var WORLDLE_DATA = {
  aliases: {
    "The Trapper": ["trapper", "evan", "evan macmillan"],
    "The Wraith": ["wraith", "philip", "philip ojomo", "bing bong"],
    "The Hillbilly": ["hillbilly", "billy", "max", "max thompson"],
    "The Nurse": ["nurse", "sally", "sally smithson"],
    "The Hag": ["hag", "lisa", "lisa sherwood"],
    "The Shape": ["shape", "myers", "michael", "michael myers"],
    "The Doctor": ["doctor", "doc", "herman", "herman carter"],
    "The Huntress": ["huntress", "anna"],
    "The Cannibal": ["cannibal", "bubba", "bubba sawyer", "leatherface"],
    "The Nightmare": ["nightmare", "freddy", "freddy krueger"],
    "The Pig": ["pig", "amanda", "amanda young"],
    "The Clown": ["clown", "kenny", "kenneth chase"],
    "The Spirit": ["spirit", "rin", "rin yamaoka"],
    "The Legion": ["legion", "frank", "julie", "susie", "joey"],
    "The Plague": ["plague", "adiris"],
    "The Ghost Face": ["ghost face", "ghostface", "danny", "danny johnson"],
    "The Demogorgon": ["demogorgon", "demo", "the fold"],
    "The Oni": ["oni", "kazan", "kazan yamaoka"],
    "The Deathslinger": ["deathslinger", "slinger", "caleb", "caleb quinn"],
    "The Executioner": ["executioner", "pyramid head", "pyramidhead"],
    "The Blight": ["blight", "talbot", "talbot grimes"],
    "The Twins": ["twins", "charlotte", "victor"],
    "The Trickster": ["trickster", "ji woon", "ji-woon", "ji-woon hak"],
    "The Nemesis": ["nemesis", "tyrant"],
    "The Cenobite": ["cenobite", "pinhead", "elliot", "elliot spencer"],
    "The Artist": ["artist", "carmina", "carmina mora"],
    "The Onryō": ["onryo", "onryō", "sadako", "sadako yamamura"],
    "The Dredge": ["dredge", "fold"],
    "The Mastermind": ["mastermind", "wesker", "albert", "albert wesker"],
    "The Knight": ["knight", "tarhos", "tarhos kovacs"],
    "The Skull Merchant": ["skull merchant", "skullmerchant", "adriana", "adriana imai"],
    "The Singularity": ["singularity", "hux", "hux-a7-13"],
    "The Xenomorph": ["xenomorph", "xeno", "alien"],
    "The Good Guy": ["good guy", "goodguy", "chucky", "charles lee ray"],
    "The Unknown": ["unknown"],
    "The Lich": ["lich", "vecna"],
    "The Dark Lord": ["dark lord", "darklord", "dracula"],
    "The Houndmaster": ["houndmaster", "hound master", "portia", "portia maye"],
    "The Ghoul": ["ghoul", "ken", "ken kaneki"],
    "The Animatronic": ["animatronic", "springtrap", "william", "william afton"],
    "The Krasue": ["krasue", "burong", "burong sukapat"],
    "The First": ["first", "henry", "henry creel"]
  },
  genders: {
    "The Trapper": "Male",
    "The Wraith": "Male",
    "The Hillbilly": "Male",
    "The Nurse": "Female",
    "The Hag": "Female",
    "The Shape": "Male",
    "The Doctor": "Male",
    "The Huntress": "Female",
    "The Cannibal": "Male",
    "The Nightmare": "Male",
    "The Pig": "Female",
    "The Clown": "Male",
    "The Spirit": "Female",
    "The Legion": "Other",
    "The Plague": "Female",
    "The Ghost Face": "Male",
    "The Demogorgon": "Other",
    "The Oni": "Male",
    "The Deathslinger": "Male",
    "The Executioner": "Male",
    "The Blight": "Male",
    "The Twins": "Female",
    "The Trickster": "Male",
    "The Nemesis": "Male",
    "The Cenobite": "Male",
    "The Artist": "Female",
    "The Onryō": "Female",
    "The Dredge": "Other",
    "The Mastermind": "Male",
    "The Knight": "Male",
    "The Skull Merchant": "Female",
    "The Singularity": "Other",
    "The Xenomorph": "Other",
    "The Good Guy": "Male",
    "The Unknown": "Other",
    "The Lich": "Male",
    "The Dark Lord": "Male",
    "The Houndmaster": "Female",
    "The Ghoul": "Male",
    "The Animatronic": "Male",
    "The Krasue": "Female",
    "The First": "Male"
  },
  emojiClues: {
    "The Trapper": ["🪤", "⛏️", "🏭"],
    "The Wraith": ["🔔", "👻", "🫥"],
    "The Hillbilly": ["🪚", "🌽", "🏃"],
    "The Nurse": ["🏥", "💨", "🩺"],
    "The Hag": ["🔺", "🪬", "🩸"],
    "The Shape": ["🔪", "🎃", "👁️"],
    "The Doctor": ["⚡", "🧠", "😱"],
    "The Huntress": ["🪓", "🐇", "🎶"],
    "The Cannibal": ["🪚", "🥩", "🍖"],
    "The Nightmare": ["😴", "🔥", "🧤"],
    "The Pig": ["🐷", "🪤", "🎭"],
    "The Clown": ["🤡", "🍼", "💨"],
    "The Spirit": ["👻", "⚔️", "🎐"],
    "The Legion": ["🔪", "🏃", "👥"],
    "The Plague": ["🤮", "🛕", "🧪"],
    "The Ghost Face": ["📸", "😱", "👻"],
    "The Demogorgon": ["🌐", "🧬", "👹"],
    "The Oni": ["👹", "🩸", "🔨"],
    "The Deathslinger": ["🤠", "🔫", "⛓️"],
    "The Executioner": ["🔺", "🔪", "⚔️"],
    "The Blight": ["🧪", "💥", "🧟"],
    "The Twins": ["👩", "👶", "🩸"],
    "The Trickster": ["🎤", "🔪", "✨"],
    "The Nemesis": ["🧟", "💉", "👊"],
    "The Cenobite": ["📦", "⛓️", "🪝"],
    "The Artist": ["🖤", "🪶", "🐦"],
    "The Onryō": ["📼", "💍", "👻"],
    "The Dredge": ["🗄️", "🌑", "🫳"],
    "The Mastermind": ["🕶️", "🧬", "🚀"],
    "The Knight": ["🛡️", "⚔️", "🏰"],
    "The Skull Merchant": ["💀", "📡", "🗡️"],
    "The Singularity": ["🤖", "📷", "🧬"],
    "The Xenomorph": ["👽", "🥚", "🚇"],
    "The Good Guy": ["🔪", "🧸", "👦"],
    "The Unknown": ["❓", "📺", "🪓"],
    "The Lich": ["🧙", "🎲", "💀"],
    "The Dark Lord": ["🧛", "🦇", "🏰"],
    "The Houndmaster": ["🐕", "⚓", "🪝"],
    "The Ghoul": ["👁️", "🩸", "🕷️"],
    "The Animatronic": ["🐰", "🤖", "🔦"],
    "The Krasue": ["👻", "🫀", "🌙"],
    "The First": ["🕰️", "🌩️", "👁️"]
  }
};

if (typeof module !== 'undefined') {
  module.exports = WORLDLE_DATA;
}
